language: node_js
node_js: '11'

cache: yarn

install: yarn install

jobs:
  include:
    - stage: npm release
      if: branch = master AND tag IS blank
      node_js: stable
      script: yarn build
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        tag: next
    - stage: npm latest release
      if: tag IS present
      node_js: stable
      script: yarn build
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        tag: latest
        on:
          tags: true
